# - hosts: database
#   become: yes

#   roles:
#     - sql      




- hosts: webservers
  become: yes

  tasks:
  - name: "apt-get update"
    apt:
      update_cache: yes
      cache_valid_time: 3600

  - name: "install nginx"
    apt:
      name: ['nginx']
      state: latest



  - name: delete default nginx site
    file:
      path: /etc/nginx/sites-enabled/default
      state: absent
    notify: restart nginx

  
  - name: Install curl
    apt:
      name: curl
      state: present

  - name: Install wget
    apt:
      name: wget
      state: present

  - name: install nodejs
    apt: 
      name: nodejs
      state: present

  - name: install npm
    apt:
      name: npm
      state: present

  - name: Install PM2
    npm:
      name: pm2
      global: yes    

  - name: install angular
    npm: 
      name: angular
      global: yes     






    handlers:
    - name: restart nginx
      service:
        name: nginx
        state: restarted 


